import { StyleSheet } from "react-native";

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

import { colors, fontFamily, metrics } from "../../styles";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.purpleLight,
    flex: 1,
    // justifyContent: "center",
  },
  dateTimeContainer: {
    backgroundColor: colors.white,
    borderBottomEndRadius: 40,
    borderBottomStartRadius: 40,
  },
  goBackContainer: {
    // position: "absolute",
    marginTop: hp(2),
    marginLeft: wp(2),
    // backgroundColor: colors.darkTransparent,
    width: metrics.goBackIconSize + 7,
    borderRadius: metrics.borderRadius,
    height: metrics.goBackIconSize + 7,
    alignItems: "center",
    justifyContent: "center",
  },
  separator: {
    marginVertical: wp(4),
    height: 1,
    width: "80%",
  },
  sectionContainer: {
    // backgroundColor: colors.pink,
    width: wp(90),
    alignSelf: "center",
  },
  screenTitle: {
    color: colors.purpleDarker,
    fontSize: metrics.fontSize20,
    fontFamily: fontFamily.notoSans_bold,
  },
  sectionTitle: {
    fontFamily: fontFamily.notoSans_bold,
    fontSize: metrics.fontSize19,
  },
  dateItemView: {
    backgroundColor: colors.white,
    alignSelf: "center",
    alignItems: "center",
    width: 50,
    padding: 5,
    margin: 5,
    elevation: 2,
    borderRadius: metrics.borderRadius,
  },
  dateItemSelectedView: {
    backgroundColor: colors.purpleLight,
    alignSelf: "center",
    alignItems: "center",
    width: 50,
    padding: 5,
    margin: 5,
    elevation: 2,
    borderRadius: metrics.borderRadius,
  },
  dateText: {
    color: colors.purpleDarker,
    fontFamily: fontFamily.notoSans_medium,
    fontSize: metrics.fontSize16,
  },
  timeItemView: {
    backgroundColor: colors.purpleLight,
    width: wp(28),
    height: wp(10),
    marginBottom: wp(4),
    borderRadius: metrics.borderRadius,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    marginRight: wp(5),
  },
  timeItemSelectedView: {
    backgroundColor: colors.purple,
    width: wp(28),
    height: wp(10),
    marginBottom: wp(4),
    borderRadius: metrics.borderRadius,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    marginRight: wp(5),
  },
  timeText: {
    color: colors.purpleDarker,
    fontFamily: fontFamily.notoSans_medium,
    fontSize: metrics.fontSize15,
  },
  timeSelectedText: {
    color: colors.white,
    fontFamily: fontFamily.notoSans_medium,
    fontSize: metrics.fontSize15,
  },
  petShopItemView: {
    paddingVertical: 5,
    // flexDirection: "row",
    flex: 1,
    backgroundColor: colors.white,
    width: wp(90),
    // height: wp(30),
    marginBottom: wp(4),
    borderRadius: metrics.borderRadius,
    // borderColor: colors.purple,
    // borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
  },
  petShopItemImageView: {
    // backgroundColor: colors.blue,
    flexDirection: "row",
    flex: 1,
    width: wp(90),
    alignItems: "center",
    // height: wp(30),
  },
  petShopName: {
    alignSelf: "flex-start",

    color: colors.purpleDarker,
    fontSize: metrics.fontSize15,
    fontFamily: fontFamily.notoSans_bold,
  },
  petShopInfos: {
    alignSelf: "flex-start",
    fontSize: metrics.fontSize11,
    fontFamily: fontFamily.notoSans_regular,
    color: colors.greyDark,
    marginVertical: 1,
  },
});
